spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/reddit?serverTimezone=UTC
    username: waffle-team-4
    password: waffleteam4
    sql:
      init:
        mode: always
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: prod1

  datasource:
    url: jdbc:mysql://waffle-toy4-db.c44j4eo5ddlj.ap-northeast-2.rds.amazonaws.com:3306/reddit?serverTimezone=UTC
    username: waffle-team-4
    password: waffleteam4
    sql:
      init:
        mode: always
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: update
server:
    port: 8081
