spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/reddit?serverTimezone=UTC
    username: admin
    password: ??
    sql:
      init:
        mode: always
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://waffle-toy4-db.c44j4eo5ddlj.ap-northeast-2.rds.amazonaws.com:3306/reddit?serverTimezone=UTC
    username: admin
    password: waffle_toy4_backend
    sql:
      init:
        mode: always
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: update