cloud:
    aws:
        s3:
            bucket: waffle-team-4-server-s3
        region:
            static: ap-northeast-2
        stack:
            auto: false
        credentials:
            instanceProfile: true
