name: Deploy with AWS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew

    - name: Inject application-oauth.ym
      env:
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
      run: |
          echo -e "oauth2:\n    user:\n        google:\n            client-id: $OAUTH_CLIENT_ID\n            client-secret: $OAUTH_CLIENT_SECRET\n            redirect-uri: http://localhost:8080/redirect/oauth\n    provider:\n        google:\n            token-uri: https://www.googleapis.com/oauth2/v4/token\n            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo\n" > ./src/main/resources/application-oauth.yml

    - name: Export JAR with Gradle
      run: |
        ./gradlew bootJar --no-daemon

    - name: Make Directory for deliver
      run: mkdir deploy

    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy/

    - name: Copy appspec
      run: cp ./deployment/appspec.yml ./deploy/

    - name: Copy shell
      run: cp ./scripts/bash/* ./deploy/

    - name: Make zip file
      run: zip -r -qq -j ./waffle-team-4-server-build.zip ./deploy

    - name: Deliver to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./waffle-team-4-server-build.zip s3://waffle-team-4-server-s3/

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name waffle-team-4-server-application \
        --deployment-group-name waffle-team-4-server-deploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=waffle-team-4-server-s3,bundleType=zip,key=waffle-team-4-server-build.zip \
        --region ap-northeast-2

    - name: Cleanup Gradle Cache
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties

