name: Run test with Gradle

on:
    push:
        branches: [master]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: Set up MySQL
              uses: samin/mysql-action@v1
              with:
                  charcter set server: 'utf8'
                  mysql database: 'reddit_test'
                  mysql user: 'waffle-team-4'
                  mysql password: 'waffleteam4'

            - name: Cache Gradle packages
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Grant execute permission for gradlew
              run: |
                  chmod +x gradlew

            - name: Run test
              run: |
                  ./gradlew test --no-daemon

            - name: Publish test results
              uses: EnricoMi/publish-unit-test-result-action@v1
              if: ${{ always() }}
              with:
                  files: ./build/test-results/**/*.xml

            - name: Cleanup Gradle Cache
              run: |
                  rm -f ~/.gradle/caches/modules-2/modules-2.lock
                  rm -f ~/.gradle/caches/modules-2/gc.properties

